# Generated by Django 3.1.3 on 2020-12-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('model_variant', models.CharField(max_length=50)),
                ('production_year', models.IntegerField(max_length=5)),
                ('engine_power', models.IntegerField(max_length=5)),
                ('mileage', models.IntegerField(max_length=20)),
                ('engine_capacity', models.FloatField(max_length=5)),
                ('offer_type', models.CharField(max_length=10)),
                ('price', models.IntegerField(max_length=20)),
                ('price_currency', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=10)),
            ],
        ),
    ]
