# Generated by Django 3.1.3 on 2020-12-15 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices_tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_power',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='production_year',
            field=models.IntegerField(),
        ),
    ]
