# Generated by Django 3.1.3 on 2021-01-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices_tool', '0002_auto_20201215_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='price_dollars',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
