# Generated by Django 3.1.3 on 2021-02-20 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices_tool', '0008_auto_20210123_1807'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarMake',
        ),
    ]
