# Generated by Django 3.1.7 on 2021-03-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_prices_tool', '0010_auto_20210222_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model_variant',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
